import "./SkillsBlock.css";

function SkillsBlock() {
  return (
    <table class="skills-block">
      <thead>
        <tr>
          <th>Proficiency</th>
          <th>Name</th>
          <th>Modifier</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Yes</td>
          <td>Acrobatics</td>
          <td>+3</td>
        </tr>
        <tr>
          <td>No</td>
          <td>Animal Handling</td>
          <td>+1</td>
        </tr>
        <tr>
          <td>Yes</td>
          <td>Arcana</td>
          <td>+2</td>
        </tr>
        <tr>
          <td>No</td>
          <td>Athletics</td>
          <td>+1</td>
        </tr>
        <tr>
          <td>Yes</td>
          <td>Deception</td>
          <td>+4</td>
        </tr>
        <tr>
          <td>Yes</td>
          <td>History</td>
          <td>+2</td>
        </tr>
        <tr>
          <td>Yes</td>
          <td>Insight</td>
          <td>+3</td>
        </tr>
        <tr>
          <td>Yes</td>
          <td>Intimidation</td>
          <td>+2</td>
        </tr>
        <tr>
          <td>Yes</td>
          <td>Investigation</td>
          <td>+2</td>
        </tr>
        <tr>
          <td>Yes</td>
          <td>Medicine</td>
          <td>+2</td>
        </tr>
        <tr>
          <td>Yes</td>
          <td>Nature</td>
          <td>+2</td>
        </tr>
        <tr>
          <td>Yes</td>
          <td>Perception</td>
          <td>+3</td>
        </tr>
        <tr>
          <td>Yes</td>
          <td>Performance</td>
          <td>+4</td>
        </tr>
        <tr>
          <td>Yes</td>
          <td>Persuasion</td>
          <td>+4</td>
        </tr>
        <tr>
          <td>Yes</td>
          <td>Religion</td>
          <td>+2</td>
        </tr>
        <tr>
          <td>Yes</td>
          <td>Sleight of Hand</td>
          <td>+3</td>
        </tr>
        <tr>
          <td>Yes</td>
          <td>Stealth</td>
          <td>+3</td>
        </tr>
        <tr>
          <td>Yes</td>
          <td>Survival</td>
          <td>+2</td>
        </tr>
      </tbody>
    </table>
  );
}

export default SkillsBlock;
